### ISSUE TITLE
HTTP response header should be case-insensitive

### ISSUE THREAD

**Issue by antoine-roux** [ILLGrenoble/visa-api-server#1]
Hello,
Some reverse-proxy/load-balancer in front of OpenStack lower the case of the HTTP response headers.

For example, HAProxy returns a `x-subject-token` instead of `X-Subject-Token` while authenticating.
Because of that, the OpenStackProvider is unable to get the token from Keystone.

At https://github.com/ILLGrenoble/visa-api-server/blob/main/visa-cloud/src/main/java/eu/ill/visa/cloud/http/HttpResponse.java#L30 the `getHeader` method should be able to get the header regardless of the case.

Meanwhile, I added a specific configuration to HAProxy to bypass that issue (https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#no%20option%20http-use-htx), but I think it could be better if VISA was case-insensitive.

See you,
Antoine

**Comment by stuartcaunt** [comment]
Hello!

Thanks for spotting this and it seems to be a recurring problem. The code's been changed now to fix this (currently in the dev branch) and it'll be available in the next release (next week probably).

Cheers,
Stuart
